"""initial migration

Revision ID: 1a9b4aedd342
Revises: 
Create Date: 2025-12-22 21:58:08.672687

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1a9b4aedd342'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Enum('ADMIN', 'STUDENT', 'FACULTY', 'PROFESSOR', name='userrole'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('ADMIN', 'STUDENT', 'FACULTY', 'PROFESSOR', name='userrole'),
               type_=mysql.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###
